- name: Setup Bricks
  hosts: hc_nodes
  remote_user: root
  gather_facts: yes

  vars:
    gluster_features_hci_packages: []
    gluster_features_hci_cluster: "{{ groups['hc_nodes'] }}"
    gluster_infra_lv_thinpoolname: gluster_thinpool
  pre_tasks:
    - name: Install ansible dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python-jwt
        - python-requests
        - policycoreutils-python
  roles:
    - gluster.infra
  tags:
    - wizard_bricks


- name: Deploy HCI
  hosts: local
  vars:

    gluster_features_hci_master: localhost
    gluster_features_hci_cluster: "{{ groups['hc_nodes'] }}"
  roles:
    - gluster.features
  tags:
    - wizard_volumes
